###
# Get index
GET {{baseUrl}}/

###
# Push update to test-sensor
POST {{baseUrl}}/sensor/v1/update
Content-Type: application/json
Authorization: Bearer /innopolis/dorms/1/levels/3/washers/1

{"state":"active"}

###
# Push update to another-test-sensor
POST {{baseUrl}}/sensor/v1/update
Content-Type: application/json
Authorization: Bearer /innopolis/dorms/1/levels/3/washers/2

{"state":"inactive"}

###
# Get status
GET {{baseUrl}}/status/v1
